-- @description A fennel repl for reaper
-- @version 0.0.4
-- @author pbaille
-- @about
--   # Fennel repl
--   TODO
-- @provides
--    [main] pbaille_start fennel repl.lua
--    [nomain] ../lib/*.lua
--    [nomain] ../compiled/*.lua
--    [nomain] ../lib/socket module/socket/core.dll
--    [nomain] ../lib/socket module/socket/core.so
--    [nomain] ../lib/socket module/socket/core.so.linux
