#!/bin/bash

DIRS=("src/fennel" "lib/fennel")
SCRIPT="scripts/compile-fennel"

fswatch -o "${DIRS[@]}" | while read -r event
do
    echo "Change detected in one of the dirs, running $SCRIPT"
    bash "$SCRIPT"
done
